### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by evgenyneu** [jcjones/crlite_status#4]
Hi, I get this error when running the tool `crlite_status 8`
 
 ```
 File "crlite_status/.venv/lib/python3.12/site-packages/crlite_status/status.py", line 109, in _get_remote_path
    raise FileNotFoundException(f"{remote_path} does not exist")
crlite_status.status.FileNotFoundException: 20240820-0/mlbf/stats.json does not exist
```

Looks like it can not find the stats.json file in the google cloud bucket?

**Comment by jcjones** [comment]
It looks like Mozilla no longer publishes the `stats.json` file [in each run](https://console.cloud.google.com/storage/browser/crlite-filters-prod/20240811-3/mlbf?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))). 

I've made a minimal fix in https://github.com/jcjones/crlite_status/commit/92f36f977e0fae4856545c4927e8ab5a1c173548, which I'll work to go produce a release of.

That said, probably this tool should just be marked as unmaintained, as I no longer have any direct part in the CRLite ecosystem -- except insomuch as I make sure it gets tons of data from Let's Encrypt.

**Comment by jcjones** [comment]
Published to https://pypi.org/project/crlite-status/0.0.8/

**Comment by evgenyneu** [comment]
Thank you for the info! 👍
